# Generated by Django 4.2.3 on 2023-07-20 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('epic_events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaborator',
            name='role',
        ),
        migrations.AddField(
            model_name='collaborator',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group'),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
