# Generated by Django 4.2.3 on 2023-07-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic_events', '0004_alter_client_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
